# .github/workflows/ci.yml

name: CI                          # Display name in GitHub UI

on:                               # TRIGGER: when does this run?
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:                           # JOB name (can have many jobs)
    runs-on: ubuntu-latest        # Runner OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v1          # Clone your repo
          
      - name: Get hostname
        run: hostname                    # Shell command

      - name: Get date
        run: date +%s

      - name: Get files
        run: ls
          
      - name: Install TF
        run: sudo ./scripts/install.sh

      - name: Download Data
        run: wget https://github.com/ketancmaheshwari/impecc-data/raw/refs/heads/main/BDB.tgz

      - name: Untar Data
        run: tar zxvf BDB.tgz
